/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib */

#ifndef _Included_com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
#define _Included_com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    getPartition
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_getPartition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    lsCommand
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_lsCommand
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    cdCommand
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_cdCommand
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    cpCommand
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_cpCommand
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    helpCommand
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_helpCommand
  (JNIEnv *, jobject);

/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ScriptModeLib
 * Method:    exitCommand
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ScriptModeLib_exitCommand
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
