/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ifmo_ttaaa_ss_lab3_app_ListModeLib */

#ifndef _Included_com_ifmo_ttaaa_ss_lab3_app_ListModeLib
#define _Included_com_ifmo_ttaaa_ss_lab3_app_ListModeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifmo_ttaaa_ss_lab3_app_ListModeLib
 * Method:    runListMode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ifmo_ttaaa_ss_1lab3_app_ListModeLib_runListMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
